<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd8a157c87e6901ad4261d4ba68b1ba2b
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'ShrinkPress\\Mail\\' => 17,
            'ShrinkPress\\Atom\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ShrinkPress\\Mail\\' => 
        array (
            0 => __DIR__ . '/..' . '/shrinkpress/mail/src',
        ),
        'ShrinkPress\\Atom\\' => 
        array (
            0 => __DIR__ . '/..' . '/shrinkpress/atom/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd8a157c87e6901ad4261d4ba68b1ba2b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd8a157c87e6901ad4261d4ba68b1ba2b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
