<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ShrinkPress\\Mail\\' => array($vendorDir . '/shrinkpress/mail/src'),
    'ShrinkPress\\Atom\\' => array($vendorDir . '/shrinkpress/atom/src'),
);
